name: NametagPlugin
version: 1.0.0
main: com.nametag.NametagPlugin
api-version: '1.21'
description: Custom nametag display using TextDisplay entities

# Soft dependencies - plugin works without these but has reduced functionality
softdepend:
  - LuckPerms
  - PlaceholderAPI
  - SuperVanish
  - PremiumVanish

author: ItzStevee
